SURF_CLUBS = {
    "Austinmer Surf Life Saving Club": "Austinmer Beach",
    "Avalon Beach Surf Life Saving Club": "Avalon Beach",
    "Ballina Lighthouse $ Lismore Surf Life Saving Club": "Lighthouse Beach",
    "Bellambi Surf Life Saving Club": "Bellambi Beach",
    "Bermagui Surf Life Saving Club": "Main Beach",
    "Bondi Surf Bathers Life Saving Club": "Bondi Beach",
    "Bronte Surf Life Saving Club": "Bronte Beach",
    "Bulli Surf Life Saving Club": "Bulli Beach",
    "Byron Bay Surf Life Saving Club": "Clarkes Beach",
    "Cabarita Beach Surf Life Saving Club": "Cabarita Beach",
    "Catherine Hill Bay Surf Life Saving Club": "Catherine Hill Bay Beach",
    "Clovelly Surf Life Saving Club": "Clovelly Beach",
    "Coffs Harbour Surf Life Saving Club": "Park Beach",
    "Collaroy Surf Life Saving Club": "Collaroy Beach",
    "Copacobana Surf Life Saving Club": "Copacabana Beach",
    "Cronulla Surf Life Saving Club": "Cronulla Beach",
    "Crowdy Bay Surf Life Saving Club": "Crowdy Bay Beach",
    "Dee Why Surf Life Saving Club": "Dee Why Beach",
    "Fingal Rovers Surf Life Saving Club": "Fingal Head Beach",
    "Garie Surf Living Saving Club": "Garie Beach",
    "Hat Head Surf Life Saving Club": "Connors Beach",
    "Helensburgh-Stanwell Park Surf Life Saving Club": "Stanwell Park Beach",
    "Kempsey Cresent Head Surf Life Saving Club": "Killick Beach",
    "Kingscliff Surf Club": "Kingscliff Beach",
    "Long Reef Surf Life Saving Club": "Long Reef Beach",
    "MacMasters Beach Surf Life Saving Club": "MacMasters Beach",
    "Manly Surf Life Saving Club": "Manly Beach",
    "Mereweather Surf Life Saving Club": "Mereweather Beach",
    "Mona Vale Surf Life Saving Club": "Mona Vale Beach",
    "Narooma Surf Life Saving Club": "Narooma Beach",
    "Newcastle Surf Life Saving Club": "Newcastle Beach",
    "Nobbys Surf Life Saving Club": "Nobbys Beach",
    "North Avoca Surf Life Saving Club": "North Avoca Beach",
    "North Bondi Surf Life Saving Club": "Bondi Beach",
    "North Cronulla Surf Life Saving Club": "North Cronulla Beach",
    "North Palm Beach Surf Life Saving Club": "Palm Beach",
    "North Steyne Surf Life Saving Club": "Nort Steyne Beach",
    "North Wollongong Surf Life Saving Club": "North Wollongong Beach",
    "Ocean Beach Surf Life Saving Club": "Ocean Beach",
    "Port Macquarie Surf Life Saving Club": "Flynns Beach",
    "Queenscliff Surf Life Saving Club": "Queenscliff Beach",
    "Sawtell Surf Life Saving Club": "Sawtell Main Beach",
    "Shelly Beach Surf Lifesaving Club": "Shelly Beach",
    "Soldiers Beach Surf Lifesaving Club": "Soldiers Beach",
    "South Maroubra Surf Life Saving Club": "Maroubra Beach",
    "South Narrabeen Surf Life Saving Club": "Collaroy Beach",
    "Surf Life Saving Far North Coast": "Shelly Beach",
    "Swansea Belmont Surf Life Saving Club": "Blacksmiths Beach",
    "Tamarama Surf Life Saving Club": "Tamarama Beach",
    "Tea Gardens Hawks Nest Surf Life Saving Club": "Bennetts Beach",
    "Terrigal Surf Life Saving Club": "Terrigal Beach",
    "The Entrance Surf Life Saving Club": "Keating Beach",
    "Thirroul Surf Life Saving Club": "Thirroul Beach",
    "Toowoon Bay Surf Life Saving Club": "Toowoon Bay Beach",
    "Towradgi Surf Club": "Towradgi Beach",
    "Umina Surf Life Saving Club": "Umina Main Beach",
    "Wamberal Surf Lifesaving Club": "Wamberal Beach",
    "Wanda Surf Life Saving Club": "Wanda Beach",
    "Warriewood Surf Life Saving Club": "Warriewood Beach",
    "Windang City Surf Life Saving Club": "Windang Beach",
    "Wollongong City Surf Life Saving Club": "Wollongong City Beach",
    "Woolgoolga Surf Life Saving Club": "Woolgoolga Beach",
    "Yamba Surf Life Saving Club": "Yamba Main Beach",
}


def convert_lifeguard_name(name):
    if name in SURF_CLUBS:
        return SURF_CLUBS[name]
    print(f"Could not convert lifeguard name {name}")
